driver:
  name: molecule-proxmox
  options:
    debug: true
    # Provide the absolute path to the secrets.yml file. I cannot get this to work with a relative path ATM
    proxmox_secrets: <<full path>>
    node: <<hostname of proxmox server>>
    ssh_port: 22
    ssh_identity_file: <<path to the private key>>
    timeout: 300


# Define the platforms to test on. In this basic case, there is a single Rocky 9 platform
platforms:
  - name: molecule-rocky9
    template_name: << Name of the template as seen in the Proxmox GUI>>
    ostype: l26
    hostname: << name of the host to create for this test eg: molecule-rocky9-test>>
    ssh_private_key_file: << full path to the private key >>


provisioner:
  name: ansible
  log: true
  config_options:
    ssh-connection:
      host_key_checking: false
  connection_options:
    ansible_ssh_user: "ansible"
    ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o ControlMaster=auto
        -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes
        -o StrictHostKeyChecking=no
  lint:
    name: "ansible-lint"


verifier:
  name: ansible
  enabled: true
  directory: ../../tests

